export enum GameEventType {
  BATTLE_REWARD_GENERATED = 'BATTLE_REWARD_GENERATED',
  SPAWN_MONSTER = 'SPAWN_MONSTER',
  COMPLETE_EVENT = 'COMPLETE_EVENT',
  SKILL_RAISE_SKELETON_SUCCESS = 'SKILL_RAISE_SKELETON_SUCCESS',
  NPC_IS_DEAD = 'NPC_IS_DEAD',
  SYSTEM_EXIT = 'SYSTEM_EXIT'

  // 전투 관련
  // MONSTER_DIED = 'MONSTER_DIED',
  // BATTLE_START = 'BATTLE_START',
  // BATTLE_END = 'BATTLE_END',
  // UNIT_REGISTERED = 'UNIT_REGISTERED',
  
  // 월드/시스템 관련
  // ITEM_DROPPED = 'ITEM_DROPPED',
  // LOG_MESSAGE = 'LOG_MESSAGE',
  // PLAYER_HEALED = 'PLAYER_HEALED',
  // TERMINAL_CLEAR = 'TERMINAL_CLEAR'
}