import { SKILL_IDS, Skill, SkillId } from '../../types'
import { Player } from '../Player'
import { SkillExecutor } from './executors'

export const SKILL_LIST: Record<SkillId, Skill> = {
  [SKILL_IDS.RAISE_SKELETON]: {
    id: SKILL_IDS.RAISE_SKELETON,
    name: '스켈레톤 생성',
    description: '시체를 소모하여 해골 병사를 소환합니다.',
    cost: 10,
    requiredExp: 0,
    requiredLevel: 1,
    unlocks: [],
    unlockHint: '',
    execute: (player, context) => SkillExecutor.raiseSkeleton(player, context),
  },
  [SKILL_IDS.FOCUS_FIRE]: {
    id: SKILL_IDS.FOCUS_FIRE,
    name: '죽음의 표식',
    description:
      '지정한 적에게 죽음의 표식을 남깁니다. 소환된 모든 해골 병사가 즉시 해당 대상을 우선적으로 공격합니다.',
    cost: 5,
    requiredExp: 0,
    requiredLevel: 1,
    unlocks: [],
    unlockHint: '',
    execute: (player, context, units) => SkillExecutor.focusFire(player, context, units),
  },
  [SKILL_IDS.SOUL_HARVEST]: {
    id: SKILL_IDS.SOUL_HARVEST,
    name: '영혼 흡수',
    description: '시체에서 정수를 뽑아내 마나로 전환합니다.',
    cost: 0,
    requiredExp: 500,
    requiredLevel: 2,
    unlocks: ['first_boss'],
    unlockHint: '지하 2층 정화 완료',
    execute: (player, context) => SkillExecutor.soulHarvest(player, context),
  },
  [SKILL_IDS.CORPSE_EXPLOSION]: {
    id: SKILL_IDS.CORPSE_EXPLOSION,
    name: '시체 폭발',
    description: '시체를 폭파시켜 광역 피해를 입힙니다.',
    cost: 15,
    requiredExp: 800,
    requiredLevel: 3,
    unlocks: ['first_boss'],
    unlockHint: '지하 2층 정화 완료',
    execute: (player, context, units) => SkillExecutor.corpseExplosion(player, context, units),
  },
  [SKILL_IDS.SOUL_TRANSFER]: {
    id: SKILL_IDS.SOUL_TRANSFER,
    name: '영혼 전달',
    description: '종속에게 이로운 효과를 부여합니다.',
    cost: 5,
    requiredExp: 600,
    requiredLevel: 3,
    unlocks: ['second_boss'],
    unlockHint: '지하 3층 정화 완료',
    execute: (player, context, units) => SkillExecutor.soulTransfer(player, context, units),
  },
  [SKILL_IDS.CURSE]: {
    id: SKILL_IDS.CURSE,
    name: '저주',
    description: '대상을 약화시킵니다.',
    cost: 10,
    requiredExp: 1000,
    requiredLevel: 3,
    unlocks: ['second_boss'],
    unlockHint: '지하 3층 정화 완료',
    execute: (player, context, units) => SkillExecutor.curse(player, context, units),
  },
  [SKILL_IDS.BONE_SPEAR]: {
    id: SKILL_IDS.BONE_SPEAR,
    name: '뼈 창',
    description: '두 적을 동시에 공격합니다.',
    cost: 12,
    requiredExp: 1500,
    requiredLevel: 3,
    unlocks: ['third_boss'],
    unlockHint: '지하 2층 정화 완료',
    execute: (player, context, units) => SkillExecutor.boneSpear(player, context, units),
  },
  [SKILL_IDS.BONE_PRISON]: {
    id: SKILL_IDS.BONE_PRISON,
    name: '뼈 감옥',
    description: '대상을 선택한 뒤 뼈를 사용해 대상의 움직임을 봉쇄합니다.',
    cost: 20,
    requiredExp: 1200,
    requiredLevel: 3,
    unlocks: ['third_boss'],
    unlockHint: '지하 4층 정화 완료',
    execute: (player, context, units) => SkillExecutor.bonePrison(player, context, units),
  },
  [SKILL_IDS.BONE_STORM]: {
    id: SKILL_IDS.BONE_STORM,
    name: '뼈 폭풍',
    description: '모든 스켈레톤을 희생하고 스켈레톤 체력의 합에 비례하여 적에게 광역대미지를 입힌다',
    cost: 60,
    requiredExp: 2000,
    requiredLevel: 3,
    unlocks: ['third_boss'],
    unlockHint: '지하 4층 정화 완료',
    execute: (player, context, units) => SkillExecutor.boneStorm(player, context, units),
  },
}

export const SkillUtils = {
  canLearn: (player: Player, skill: Skill): boolean => {
    return player.level >= skill.requiredLevel && player.exp >= skill.requiredExp
  },
}
